pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-v /tmp:/tmp'  // Optionally, you can add volume mounts here
        }
    }
    environment {
        // Environment and Project
        ENV_TYPE = "develop"
        PROJECT = "python-app"

        // Image tag
        NAME = ""
        VERSION = "0.1.${BUILD_NUMBER}-${ENV_TYPE}"
        TAG = "${NAME}:${VERSION}"

        // Mail
        MAIL_FROM = "jenkins@example.com"
        MAIL_TO = "paramwalia1998@gmail.com"
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'bash pipeline/build/build.sh'
                }
            }
        }
        stage('Code Quality') {
            steps {
                script {
                    sh 'bash pipeline/quality/quality.sh'
                }
            }
        }
        stage('Security Scan') {
            steps {
                script {
                    sh 'bash pipeline/security/security.sh'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'bash pipeline/test/test.sh'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh 'bash pipeline/push/push.sh'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'bash pipeline/deploy/deploy.sh'
                }
            }
        }
    }
    post {
        always {
            script {
                echo 'Sending status via email'
                emailext (
                    subject: "[${currentBuild.currentResult}] Jenkins PythonApp | ${env.JOB_NAME} | #${env.BUILD_NUMBER}",
                    body: """
                    Please find below job details for Jenkins PythonApp:

                    Job Name    : ${env.JOB_NAME}
                    Job Number  : ${env.BUILD_NUMBER}
                    Job Status  : ${currentBuild.result}
                    Job URL     : ${env.BUILD_URL}

                    Note: This is an autogenerated email. Please visit ${env.BUILD_URL} for more details.
                    """,
                    to: "${MAIL_TO}",
                    from: "${MAIL_FROM}"
                )
            }
        }
    }
}
